# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  


  desc "Submit a new beta build to Firebase App Distribution"
    lane :distribute do
        build_android_app(
          task: "assemble",
          build_type: "debug"
        )
        firebase_app_distribution(
            app: "1:392557441259:android:5ad2893b6bba892aaaceae",
            testers: "dohalefhal4@gmail.com,elbouhatiimad@gmail.com",
            firebase_cli_token: "1//03f_87Ru6CS5NCgYIARAAGAMSNwF-L9IrPj638N-RetT1r77CY7yS2EkBEJwmgWjTNTbBTcp4bnOFs7UZoDd4_bTJwuD36RnP9MI"
        )
    end

end
